### ISSUE TITLE
package `co` is not installed through npm install ilp-core

### ISSUE THREAD

**Issue by diminator** [interledger/js-ilp-core#17]
Had to install it manually... maybe it's an older version of the package on npm?

`node version: 6.2.2`

`npm install --save ilp-core ilp-plugin-bells`

```
 $node
> const { Client } = require('ilp-core')
undefined
> Client
[Function: Client]
> const client = new Client({
...   type: 'bells',
...   auth: {
.....     account: 'https://red.ilpdemo.org/ledger/accounts/alice',
.....     password: 'alice'
.....   }
... })
Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dimi/code_ascribe/PAYS-platform/node_modules/co-defer/index.js:1:72)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dimi/code_ascribe/PAYS-platform/node_modules/five-bells-shared/lib/notificationScheduler.js:3:15)
    at Module._compile (module.js:541:32)
... })

```

**Comment by emschwartz** [comment]
That looks like it might be a bug with `npm`. `co` is listed as a dependency. In the past I've seen a bug where `npm` just doesn't install all the deps (I know, ugh). Maybe just try installing again

**Comment by diminator** [comment]
yeah, looks like so - maybe we can digg deeper when someone else reporst this

**Comment by emschwartz** [comment]
Strange, it actually looks like it's complaining about this line in `five-bells-shared`: https://github.com/interledger/five-bells-shared/blob/master/lib/notificationScheduler.js#L3

What version of npm do you have?

**Comment by diminator** [comment]
npm version: 3.9.5
node version: 6.2.2
